### ISSUE TITLE
[BUG][PERFORMANCE] Error Occurred when open server

### ISSUE THREAD

**Issue by noodles8436** [noodles8436/THE-CROSS#41]
<em>Please make sure that this is an issue related to performance of THE-CROSS</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Education
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: X
- Python version: 3.6
- CUDA/cuDNN version: 11.4
- GPU model and memory: Geforce GTX 1050 Ti 4GB

**Describe the current behavior**
An error occurred while opening the server.

**Describe the expected behavior**
There should be no error in the process of opening the server, and a message should appear that the socket has been opened at the end.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "Server.py", line 42, in <module>
    startServer()
  File "Server.py", line 37, in startServer
    from DetectorServer import DetectorServer
  File "C:\Users\Developer KTW\THE-CROSS\DetectorServer.py", line 7, in <module>
    import ImageDetector
  File "C:\Users\Developer KTW\THE-CROSS\ImageDetector.py", line 6, in <module>
    detector = hub.load("https://tfhub.dev/tensorflow/efficientdet/lite2/detection/1")
  File "C:\Users\Developer KTW\.conda\envs\cross3.6\lib\site-packages\tensorflow_hub\module_v2.py", line 106, in load
    obj = tf.compat.v1.saved_model.load_v2(module_path, tags=tags)
  File "C:\Users\Developer KTW\.conda\envs\cross3.6\lib\site-packages\tensorflow\python\saved_model\load.py", line 864, in load
    result = load_internal(export_dir, tags, options)["root"]
  File "C:\Users\Developer KTW\.conda\envs\cross3.6\lib\site-packages\tensorflow\python\saved_model\load.py", line 878, in load_internal
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "C:\Users\Developer KTW\.conda\envs\cross3.6\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 60, in parse_saved_model_with_debug_info
    saved_model = _parse_saved_model(export_dir)
  File "C:\Users\Developer KTW\.conda\envs\cross3.6\lib\site-packages\tensorflow\python\saved_model\loader_impl.py", line 121, in parse_saved_model
    constants.SAVED_MODEL_FILENAME_PB))
OSError: SavedModel file does not exist at: C:\Users\DEVELO~1\AppData\Local\Temp\tfhub_modules\24bb465e50a79c2a6a9fc14c28388204734598a5\{saved_model.pbtxt|saved_model.pb}
```

**Comment by noodles8436** [comment]
This is an error in the Tensorflow Hub that often occurs when changing the Python version or changing the environment. Enter the address shown in the last line of the error and delete all files inside the tfhub_modules folder to resolve it.
