### ISSUE TITLE
[BUG][PERFORMANCE] Error Occurred when Server reopen Socket

### ISSUE THREAD

**Issue by noodles8436** [noodles8436/THE-CROSS#42]
<em>Please make sure that this is an issue related to performance of THE-CROSS</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Education
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: X 
- Python version: 3.8
- CUDA/cuDNN version: 11.4
- GPU model and memory: Geforce GTX 1050 Ti 4GB

**Describe the current behavior**
After the client shut down, the server failed to reopen the socket and shut down.

**Describe the expected behavior**
When the client is shut down, the server must reopen the socket.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Traceback (most recent call last):
  File "Server.py", line 42, in <module>
    startServer()
  File "Server.py", line 38, in startServer
    server = DetectorServer(IP, PORT)
  File "C:\Users\Developer KTW\THE-CROSS\DetectorServer.py", line 64, in __init__
    self.receiveImages()
  File "C:\Users\Developer KTW\THE-CROSS\DetectorServer.py", line 125, in receiveImages
    self.socketClose()
  File "C:\Users\Developer KTW\THE-CROSS\DetectorServer.py", line 69, in socketClose
    time.sleep(1)
NameError: name 'time' is not defined
```

**Comment by noodles8436** [comment]
Import time was missing from the DetectorServer.py source. This will be updated soon.
